
package es.udc.ws.jaxwstutorial.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "StockQuoteProviderService", targetNamespace = "http://ws.adoo.udc.es/", wsdlLocation = "file:/D:/Surah/workspaces/Eclipse/workspace-Practica-ADOO/ws-javaexamples/jaxwstutorial/service/target/jaxws/wsgen/wsdl/StockQuoteProviderService.wsdl")
public class StockQuoteProviderService
    extends Service
{

    private final static URL STOCKQUOTEPROVIDERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(es.udc.ws.jaxwstutorial.wsdl.StockQuoteProviderService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = es.udc.ws.jaxwstutorial.wsdl.StockQuoteProviderService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/Surah/workspaces/Eclipse/workspace-Practica-ADOO/ws-javaexamples/jaxwstutorial/service/target/jaxws/wsgen/wsdl/StockQuoteProviderService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/Surah/workspaces/Eclipse/workspace-Practica-ADOO/ws-javaexamples/jaxwstutorial/service/target/jaxws/wsgen/wsdl/StockQuoteProviderService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        STOCKQUOTEPROVIDERSERVICE_WSDL_LOCATION = url;
    }

    public StockQuoteProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StockQuoteProviderService() {
        super(STOCKQUOTEPROVIDERSERVICE_WSDL_LOCATION, new QName("http://ws.adoo.udc.es/", "StockQuoteProviderService"));
    }

    /**
     * 
     * @return
     *     returns StockQuoteProvider
     */
    @WebEndpoint(name = "StockQuoteProviderPort")
    public StockQuoteProvider getStockQuoteProviderPort() {
        return super.getPort(new QName("http://ws.adoo.udc.es/", "StockQuoteProviderPort"), StockQuoteProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockQuoteProvider
     */
    @WebEndpoint(name = "StockQuoteProviderPort")
    public StockQuoteProvider getStockQuoteProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.adoo.udc.es/", "StockQuoteProviderPort"), StockQuoteProvider.class, features);
    }

}
