
package es.udc.ws.movies.service.jaxws.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MovieInformationProviderService", targetNamespace = "http://movies.ws.adoo.udc.es/", wsdlLocation = "file:/D:/Surah/workspaces/Eclipse/workspaceADOO/ws-javaexamples-2.0.4/movies/service/target/jaxws/wsgen/wsdl/MovieInformationProviderService.wsdl")
public class MovieInformationProviderService
    extends Service
{

    private final static URL MOVIEINFORMATIONPROVIDERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(es.udc.ws.movies.service.jaxws.wsdl.MovieInformationProviderService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = es.udc.ws.movies.service.jaxws.wsdl.MovieInformationProviderService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/Surah/workspaces/Eclipse/workspaceADOO/ws-javaexamples-2.0.4/movies/service/target/jaxws/wsgen/wsdl/MovieInformationProviderService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/Surah/workspaces/Eclipse/workspaceADOO/ws-javaexamples-2.0.4/movies/service/target/jaxws/wsgen/wsdl/MovieInformationProviderService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MOVIEINFORMATIONPROVIDERSERVICE_WSDL_LOCATION = url;
    }

    public MovieInformationProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MovieInformationProviderService() {
        super(MOVIEINFORMATIONPROVIDERSERVICE_WSDL_LOCATION, new QName("http://movies.ws.adoo.udc.es/", "MovieInformationProviderService"));
    }

    /**
     * 
     * @return
     *     returns MovieInformationProvider
     */
    @WebEndpoint(name = "MovieInformationProviderPort")
    public MovieInformationProvider getMovieInformationProviderPort() {
        return super.getPort(new QName("http://movies.ws.adoo.udc.es/", "MovieInformationProviderPort"), MovieInformationProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MovieInformationProvider
     */
    @WebEndpoint(name = "MovieInformationProviderPort")
    public MovieInformationProvider getMovieInformationProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://movies.ws.adoo.udc.es/", "MovieInformationProviderPort"), MovieInformationProvider.class, features);
    }

}
