
package es.udc.ws.movies.service.jaxws.wsdl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MovieInformationProvider", targetNamespace = "http://movies.ws.adoo.udc.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MovieInformationProvider {


    /**
     * 
     * @param arg0
     * @throws MovieException
     * @throws MovieNotFoundException
     */
    @WebMethod
    @RequestWrapper(localName = "updateMovie", targetNamespace = "http://movies.ws.adoo.udc.es/", className = "es.udc.ws.movies.service.jaxws.wsdl.UpdateMovie")
    @ResponseWrapper(localName = "updateMovieResponse", targetNamespace = "http://movies.ws.adoo.udc.es/", className = "es.udc.ws.movies.service.jaxws.wsdl.UpdateMovieResponse")
    public void updateMovie(
        @WebParam(name = "arg0", targetNamespace = "")
        MovieInformationWTO arg0)
        throws MovieException, MovieNotFoundException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns long
     * @throws MovieException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addMovie", targetNamespace = "http://movies.ws.adoo.udc.es/", className = "es.udc.ws.movies.service.jaxws.wsdl.AddMovie")
    @ResponseWrapper(localName = "addMovieResponse", targetNamespace = "http://movies.ws.adoo.udc.es/", className = "es.udc.ws.movies.service.jaxws.wsdl.AddMovieResponse")
    public long addMovie(
        @WebParam(name = "arg0", targetNamespace = "")
        MovieInformationWTO arg0)
        throws MovieException
    ;

    /**
     * 
     * @param arg0
     * @throws MovieNotFoundException
     */
    @WebMethod
    @RequestWrapper(localName = "removeMovie", targetNamespace = "http://movies.ws.adoo.udc.es/", className = "es.udc.ws.movies.service.jaxws.wsdl.RemoveMovie")
    @ResponseWrapper(localName = "removeMovieResponse", targetNamespace = "http://movies.ws.adoo.udc.es/", className = "es.udc.ws.movies.service.jaxws.wsdl.RemoveMovieResponse")
    public void removeMovie(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0)
        throws MovieNotFoundException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<es.udc.ws.movies.service.jaxws.wsdl.MovieInformationWTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findMoviesByReleaseDate", targetNamespace = "http://movies.ws.adoo.udc.es/", className = "es.udc.ws.movies.service.jaxws.wsdl.FindMoviesByReleaseDate")
    @ResponseWrapper(localName = "findMoviesByReleaseDateResponse", targetNamespace = "http://movies.ws.adoo.udc.es/", className = "es.udc.ws.movies.service.jaxws.wsdl.FindMoviesByReleaseDateResponse")
    public List<MovieInformationWTO> findMoviesByReleaseDate(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0);

}
